services:
  nginx:
    image: nginx:latest
    container_name: nginx_scently
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    networks:
      - backend
    depends_on:
      - postgres
      - pgadmin
      - rabbitmq
      - products_service
  postgres:
    image: postgres:latest
    container_name: postgres_scently
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: scently
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    networks:
      - backend
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin_scently
    ports:
      - "5050:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: scently@gmail.com
      PGADMIN_DEFAULT_PASSWORD: postgres
    networks:
      - backend
    depends_on:
      - postgres
  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq_scently
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - backend
  products_service:
    build: ./products_service
    container_name: products_service_scently
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://localhost:5432/scently
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
    networks:
      - backend
    depends_on:
      - postgres
      - rabbitmq

volumes:
  postgres_data:
  pgadmin_data:

networks:
  backend:
    driver: bridge